- hosts: web
  become: true
  tasks:
    - name: Install necessary packages (NGINX, Docker, Git)
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - nginx
        - docker.io
        - git

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Clone Node.js application from Git
      git:
        repo: 'https://github.com/sakshijjj/Task1.git'
        dest: /home/ubuntu/node-app
        update: yes

    - name: Build Docker image for Node.js app
      command: docker build -t nodejs-app:latest /home/ubuntu/node-app/

    - name: Run Docker container for Node.js app
      docker_container:
        name: nodejs-app
        image: nodejs-app:latest
        state: started
        ports:
          - "3000:3000"

    - name: Configure NGINX as reverse proxy for Dockerized Node.js app
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
    
    - name: Test NGINX configuration
      command: nginx -t

    - name: Restart NGINX to apply configuration
      service:
        name: nginx
        state: restarted
